language: java
jdk: oraclejdk8
deploy:
  provider: bintray
  file: ".travis/bintray-deploy.json"
  user: "odoepner"
  key:
    secure: HgU8tOis15N5mPBHM+F6Ng98uZ8SHBsTgxJ1aMvkW2fDibRG+bIXUjbNCiWu0JChnoCGgQdT8M7WYdl63PI3kcBR272k0MobLCnplaa0X77e8xok4dNmV0fRyo9C0ov8hVQxboMqKHTK+Pw7uBhD5qD8AF778q9YRQv2AqKLkb8=
